<a href="https://colab.research.google.com/github/anmolecule/Tutorial_ML/blob/main/Tutorial_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
arr=[1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5]
nparr=np.array(arr)
nparr

array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])

In [4]:
brr=[[6, 5], [11, 7], [4, 8]]
npbrr=np.array(brr)
npbrr

array([[ 6,  5],
       [11,  7],
       [ 4,  8]])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.random.randint(low=1, high=101, size=(10))

array([58, 15, 49, 72, 62, 51,  4, 68, 67, 47])

In [13]:
np.random.random(10) 

array([0.84993359, 0.51798265, 0.28793806, 0.06304832, 0.46509094,
       0.51544882, 0.56747853, 0.1148981 , 0.52751612, 0.60142602])

In [17]:
# Scale between 3 to 5
np.random.random(10)*(5-3)+3

array([4.96130108, 3.8366504 , 3.88346679, 3.25660352, 4.86362136,
       3.0168579 , 4.69233204, 4.01678198, 3.38208131, 4.91245235])

In [18]:
#Generalize the above formula 
#Scale a random number, r generate between ra and rb to a random number between a and b. Assume b>a and rb>ra